# Generated by Django 5.2 on 2025-05-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField()),
                ('image', models.ImageField(upload_to='image/')),
                ('demo_url', models.URLField()),
                ('git_hub_url', models.URLField()),
            ],
        ),
    ]
