# Generated by Django 5.2 on 2025-05-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='juma', max_length=100),
            preserve_default=False,
        ),
    ]
